name: Pre-release Testing

on:
  push:
    tags:
      - "*"

permissions: read-all

jobs:
  prepare-release:
    name: Prepeare Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@58077d3c7e43986b6b15fba718e8ea69e387dfcc # v2.15.1
        with:
          egress-policy: audit

      - name: Build and test
        uses: myrotvorets/composite-actions/build-test-nodejs@0b8b877ead5e4e6718786803b91d295017964111
        with:
          node-version: lts/*

      - name: Create a release
        uses: softprops/action-gh-release@26e8ad27a09a225049a7075d7ec1caa2df6ff332 # v2.6.0
        if: startsWith(github.ref, 'refs/tags/')
        with:
          generate_release_notes: true
          token: ${{ secrets.REPOSITORY_ACCESS_TOKEN }}
